apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 80
      nodePort: 31001
  selector:
    app: result-deployment