apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 80
      nodePort: 31000
  selector:
    app: vote-deployment