apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote-deployment
spec:
  selector:
    matchLabels:
      app: vote-deployment      
  template:
    metadata:
      name: vote-deployment
      labels:
        app: vote-deployment
    spec:
      containers:
        - name: vote
          image: kodekloud/examplevotingapp_vote:before
          ports:
            - containerPort: 80
  replicas: 1